### ISSUE TITLE
Invariant Violation: Native component for "SRSRadialGradient" does not exist

### ISSUE THREAD

**Issue by stan-devproject** [surajitsarkar19/react-native-radial-gradient#2]
Hi! Thanks for this project!

I`m trying to get it set on a new React Native project on iOS, carefully going through your instructions.

**But got this and have no idea how to fix it:**
Invariant Violation: Native component for "SRSRadialGradient" does not exist

This error is located at:
    in SRSRadialGradient (at index.js:28)
    in RCTView (at View.js:71)
    in View (at index.js:27)
    in RadialGradient (at App.js:21)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)

getViewConfig
    requireNativeComponent.js:112:6
get$1
    ReactNativeRenderer-dev.js:11859:17
createInstance
    ReactNativeRenderer-dev.js:12022:27
completeWork
    ReactNativeRenderer-dev.js:8814:14
completeUnitOfWork
    ReactNativeRenderer-dev.js:10418:8
performUnitOfWork
    ReactNativeRenderer-dev.js:10523:32
workLoop
    ReactNativeRenderer-dev.js:10584:43
_invokeGuardedCallback
    ReactNativeRenderer-dev.js:134:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:67:32
renderRoot
    ReactNativeRenderer-dev.js:10677:30
performWorkOnRoot
    ReactNativeRenderer-dev.js:11449:34
performWork
    ReactNativeRenderer-dev.js:11364:8
requestWork
    ReactNativeRenderer-dev.js:11258:18
scheduleWorkImpl
    ReactNativeRenderer-dev.js:11099:22
scheduleRootUpdate
    ReactNativeRenderer-dev.js:11690:17
render
    ReactNativeRenderer-dev.js:12919:35
renderApplication
    renderApplication.js:58:21
runApplication
    AppRegistry.js:196:26
__callFunction
    MessageQueue.js:353:47
<unknown>
    MessageQueue.js:118:26
__guardSafe
    MessageQueue.js:316:6
callFunctionReturnFlushedQueue
    MessageQueue.js:117:17

I tried to fix this using `https://stackoverflow.com/questions/47672941/invariant-violation-native-component-for-rnsvgsvgview-does-not-exist` but this didn`t help.
Maybe you have some ideas?

**Comment by surajitsarkar19** [comment]
Hi,
Please use the latest library v1.0.2. It should solve your IOS problem.

**Comment by carmenchapa** [comment]
Hi,
I am having the same problem. Just install react-native-radial-gradient and my version is  "^1.0.3".
Any help?

Thanks!

**Comment by surajit-bitcanny** [comment]
I think you have created the react native project using **create-react-native-app**. This library renders a native view. So it will not work with projects that are created using **create-react-native-app**. You should create your project using **react-native init** or you have to convert your project to a native implementation. [Follow this link for more info](https://facebook.github.io/react-native/docs/getting-started.html)

**Comment by kashmiry** [comment]
Facing same issue, how can I fix it.
Version: 1.0.5
ReactNative version: 0.59.0
Not using expo, created with react-native init

**Comment by rajeshde** [comment]
I am using RN 0.60.4 and react-native-radial-gradient version 1.0.5

I am using Cocoapods, therefore I have included it in pod file
pod 'SRSRadialGradient', :path => '../node_modules/react-native-radial-gradient/ios'

and getting this error
Invariant Violation: requireNativeComponent: "SRSRadialGradient" was not found in the UIManager.

**Comment by 1130419** [comment]
> I am using RN 0.60.4 and react-native-radial-gradient version 1.0.5
> 
> I am using Cocoapods, therefore I have included it in pod file
> pod 'SRSRadialGradient', :path => '../node_modules/react-native-radial-gradient/ios'
> 
> and getting this error
> Invariant Violation: requireNativeComponent: "SRSRadialGradient" was not found in the UIManager.

I am using RN 0.61.2 and got the same issue

**Comment by tahalakrati** [comment]
Same here, why was this issue closed? Did you guys find a solution?

**Comment by mclant** [comment]
same issue. using Expo and "react-native-radial-gradient": "^1.1.4"

**Comment by wuguishifu** [comment]
Issue has been happening for 6 years. Anyone have a solution?
