### ISSUE TITLE
Could not find method compile() error on Android

### ISSUE THREAD

**Issue by neilakoh** [surajitsarkar19/react-native-radial-gradient#32]
Encountered an error on latest RN version 0.68.1

A problem occurred evaluating project ':react-native-radial-gradient'.
> Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

<img width="1076" alt="Screen Shot 2022-04-26 at 11 07 07 AM" src="https://user-images.githubusercontent.com/15863359/165212378-3d9c44dd-edd6-4d82-8faf-52c48ae091c1.png">

Environment:

"react": "17.0.2",
"react-native": "0.68.1",
"Platform": "Android only"

**Comment by rmesquit** [comment]
Same error for me on Android
- "react-native": "0.68.0"
- "react-native-radial-gradient": "^1.0.9"

**Comment by yzaguirre** [comment]
*compile* is not available since Gradle 7.0. Not sure how to use *implementation* with the *project* function

**Comment by yzaguirre** [comment]
This worked for me, as a temporary fix.

Edit `node_modules\react-native-radial-gradient\android\build.gradle` to replace *compile* with *implementation*.

In the `android/app/build.gradle` file use
```
implementation(project(':react-native-radial-gradient'))
```
inside the *dependencies* block.
