### ISSUE TITLE
requireNativeComponent: "SRSRadialGradient" was not found in the UIManager.

### ISSUE THREAD

**Issue by itsramiel** [surajitsarkar19/react-native-radial-gradient#45]
Hi,

I am trying to install this package to my react native, but I am getting the following error: 
`requireNativeComponent: "SRSRadialGradient" was not found in the UIManager.`

After installing in the library, I executed `pod install` int the ios directory but it did not add `SRSRadialGradient` as a dependency. I believe there is an issue with autolinking?

[Here](https://github.com/itsramiel/RadialGradientRepro) is an example repro. If you try to install and then run pod install you'll see that it doesnt add package to the podfile and you'll get the error specified above when trying to use the component

**Comment by erenkulaksiz** [comment]
+1 same happens to me.
